### ISSUE TITLE
Interaction with generators?

### ISSUE THREAD

**Issue by dead-claudia** [tc39/proposal-async-context#51] opened 2023-04-23 10:21 UTC
Question: would generators receive async context on create, or only on resume?

Based on my interpretation of the proposed spec, they'd only see what's provided on resume, but this seems pretty dangerous in my opinion. It'd be very surprising (and difficult to debug) for, say, a logger to somehow de-initialize or change targets simply due to the caller being different.

I feel generators (sync and async both) should probably have some sort of story here laid out explicitly.

**Comment by jridgewell** [comment] 2023-04-24 20:07
Closing as a duplicate of https://github.com/tc39/proposal-async-context/issues/18

**Closed by jridgewell** 2023-04-24 20:07 UTC
